# paths.yaml
# File and Directory Paths for the Protein Structure Prediction Project
paths:
  base_dir: "/home/user/protein-structure/src"
  data_dir: "data"
  models_dir: "models"
  config_dir: "config"
  templates_dir: "templates"
  static_dir: "static"
  logs_dir: "logs"
  processed_data_file: "processed_data.pkl"
  pdb_download_dir: "data/pdb"